// generated by `node lab.mjs build` from src/ (edit src/, not this file)

// addons/wand/src/main.ts
import { world as world2 } from "@minecraft/server";

// addons/wand/src/kit.ts
import {
  world,
  system,
  Player,
  ItemStack,
  CommandPermissionLevel,
  CustomCommandStatus,
  CustomCommandParamType,
  DisplaySlotId
} from "@minecraft/server";
import { ActionFormData, ModalFormData, MessageFormData, FormCancelationReason } from "@minecraft/server-ui";
var early = [];
var hooked = false;
function atStartup(fn) {
  early.push(fn);
  if (!hooked) {
    hooked = true;
    system.beforeEvents.startup.subscribe((e) => {
      for (const f of early) f(e);
    });
  }
}
var PT = {
  int: CustomCommandParamType.Integer,
  float: CustomCommandParamType.Float,
  string: CustomCommandParamType.String,
  bool: CustomCommandParamType.Boolean,
  player: CustomCommandParamType.PlayerSelector,
  entity: CustomCommandParamType.EntitySelector,
  loc: CustomCommandParamType.Location,
  item: CustomCommandParamType.ItemType,
  block: CustomCommandParamType.BlockType
};
function onItem(name, def) {
  atStartup((e) => e.itemComponentRegistry.registerCustomComponent(name, def));
}
function item(id, name, lore, n = 1) {
  const s = new ItemStack(id, n);
  if (name) s.nameTag = name;
  if (lore?.length) s.setLore(lore);
  return s;
}
var inv = (e) => e.getComponent("minecraft:inventory").container;
function give(e, item2, n) {
  const base = typeof item2 === "string" ? new ItemStack(item2) : item2;
  let left = Math.min(Math.floor(n ?? base.amount), 64 * base.maxAmount);
  const c = inv(e);
  while (left > 0) {
    const s = base.clone();
    s.amount = Math.min(left, s.maxAmount);
    left -= s.amount;
    const rest = c.addItem(s);
    if (rest) e.dimension.spawnItem(rest, e.location);
  }
}
function once(h, key) {
  const k = "kit:once:" + key;
  if (h.getDynamicProperty(k)) return false;
  h.setDynamicProperty(k, true);
  return true;
}
function score(id, name = id, show) {
  const o = world.scoreboard.getObjective(id) ?? world.scoreboard.addObjective(id, name);
  if (show) world.scoreboard.setObjectiveAtDisplaySlot(DisplaySlotId[show], { objective: o });
  return o;
}
var cds = /* @__PURE__ */ new Map();
function cooldown(e, key, ticks) {
  const k = e.id + "|" + key, now = system.currentTick;
  if ((cds.get(k) ?? -Infinity) > now) return false;
  cds.set(k, now + ticks);
  return true;
}

// addons/wand/src/main.ts
onItem("lab:wand", {
  onUse(e) {
    const p = e.source;
    if (!cooldown(p, "wand", 100)) {
      p.sendMessage("The wand is recharging");
      return;
    }
    p.addEffect("speed", 200, { amplifier: 1 });
    const s = score("wand_uses", "Wand uses", "Sidebar");
    s.addScore(p, 1);
    p.sendMessage("Whoosh!");
  }
});
world2.afterEvents.playerSpawn.subscribe((e) => {
  if (e.initialSpawn && once(e.player, "wand")) give(e.player, item("lab:wand", "Wand"), 1);
});
