// generated by `node lab.mjs build` from src/ (edit src/, not this file)

// addons/lamp/src/kit.ts
import {
  world,
  system,
  Player,
  ItemStack,
  CommandPermissionLevel,
  CustomCommandStatus,
  CustomCommandParamType,
  DisplaySlotId
} from "@minecraft/server";
import { ActionFormData, ModalFormData, MessageFormData, FormCancelationReason } from "@minecraft/server-ui";
var early = [];
var hooked = false;
function atStartup(fn) {
  early.push(fn);
  if (!hooked) {
    hooked = true;
    system.beforeEvents.startup.subscribe((e) => {
      for (const f of early) f(e);
    });
  }
}
var PT = {
  int: CustomCommandParamType.Integer,
  float: CustomCommandParamType.Float,
  string: CustomCommandParamType.String,
  bool: CustomCommandParamType.Boolean,
  player: CustomCommandParamType.PlayerSelector,
  entity: CustomCommandParamType.EntitySelector,
  loc: CustomCommandParamType.Location,
  item: CustomCommandParamType.ItemType,
  block: CustomCommandParamType.BlockType
};
function cmd(name, description, params, fn, op = false) {
  cmdAny(name, description, params, (p, a, o) => p ? fn(p, a, o) : "players only", op);
}
function cmdAny(name, description, params, fn, op = false) {
  const ns = name.split(":")[0];
  atStartup((e) => {
    const list = Object.entries(params).map(([k, t]) => {
      const opt = k.endsWith("?"), key = opt ? k.slice(0, -1) : k;
      if (Array.isArray(t)) {
        const en = `${ns}:${key}`;
        e.customCommandRegistry.registerEnum(en, [...t]);
        return { key, opt, p: { name: en, type: CustomCommandParamType.Enum } };
      }
      return { key, opt, p: { name: key, type: PT[t] } };
    });
    e.customCommandRegistry.registerCommand({
      name,
      description,
      permissionLevel: op ? CommandPermissionLevel.GameDirectors : CommandPermissionLevel.Any,
      mandatoryParameters: list.filter((x) => !x.opt).map((x) => x.p),
      optionalParameters: list.filter((x) => x.opt).map((x) => x.p)
    }, (o, ...v) => {
      const order = [...list.filter((x) => !x.opt), ...list.filter((x) => x.opt)];
      const a = {};
      order.forEach((x, i) => {
        a[x.key] = v[i];
      });
      const who = o.initiator ?? o.sourceEntity, p = who instanceof Player ? who : void 0;
      const tell = (r) => {
        if (typeof r === "string") {
          if (!p) console.warn(r);
          else if (p.isValid) p.sendMessage(r);
        }
      };
      system.run(() => {
        const r = fn(p, a, o);
        r instanceof Promise ? r.then(tell) : tell(r);
      });
      return { status: CustomCommandStatus.Success };
    });
  });
}
function onBlock(name, def) {
  atStartup((e) => e.blockComponentRegistry.registerCustomComponent(name, def));
}
async function ask(p, form, tries = 60) {
  for (let i = 0; i < tries && p.isValid; i++) {
    let r;
    try {
      r = await form.show(p);
    } catch {
      return void 0;
    }
    if (!r.canceled) return r;
    if (r.cancelationReason !== FormCancelationReason.UserBusy) return void 0;
    await system.waitTicks(5);
  }
  return void 0;
}
async function input(p, title, fields) {
  const f = new ModalFormData().title(title), keys = Object.keys(fields), kind = (t) => typeof t === "string" ? t : typeof t[0] === "number" ? "slider" : "dropdown";
  for (const k of keys) {
    const t = fields[k], c = kind(t);
    if (c === "text" || c === "number") f.textField(k, c === "number" ? "0" : "");
    else if (c === "toggle") f.toggle(k);
    else if (c === "slider") f.slider(k, t[0], t[1], { valueStep: t[2] ?? 1 });
    else f.dropdown(k, [...t]);
  }
  const r = await ask(p, f);
  if (!r?.formValues) return void 0;
  const o = {};
  keys.forEach((k, i) => {
    const t = fields[k], c = kind(t), v = r.formValues[i];
    o[k] = c === "number" ? Number(v) : c === "dropdown" ? t[v] : v;
  });
  return o;
}
function load(h, key, def) {
  const s = h.getDynamicProperty(key);
  if (typeof s !== "string") return def;
  try {
    return JSON.parse(s);
  } catch {
    return def;
  }
}
function save(h, key, v) {
  h.setDynamicProperty(key, JSON.stringify(v));
}
function getState(b, name) {
  return b.permutation.getState(name);
}
function setState(b, name, v) {
  b.setPermutation(b.permutation.withState(name, v));
}

// addons/lamp/src/main.ts
onBlock("lab:lamp", {
  onPlayerInteract(e) {
    const on = !getState(e.block, "lab:lit");
    setState(e.block, "lab:lit", on);
    e.player?.sendMessage(on ? "Lamp on" : "Lamp off");
  }
});
cmd("lab:nick", "Set your nickname", {}, async (p) => {
  const r = await input(p, "Nickname", { Name: "text" });
  if (!r) return;
  save(p, "nick", r.Name);
  return `Nickname set: ${r.Name}`;
});
cmd("lab:whoami", "Show your nickname", {}, (p) => `You are ${load(p, "nick", "(none)")}`);
