// generated by `node lab.mjs build` from src/ (edit src/, not this file)

// addons/daily/src/main.ts
import { world as world2 } from "@minecraft/server";

// addons/daily/src/kit.ts
import {
  world,
  system,
  Player,
  ItemStack,
  CommandPermissionLevel,
  CustomCommandStatus,
  CustomCommandParamType,
  DisplaySlotId
} from "@minecraft/server";
import { ActionFormData, ModalFormData, MessageFormData, FormCancelationReason } from "@minecraft/server-ui";
var PT = {
  int: CustomCommandParamType.Integer,
  float: CustomCommandParamType.Float,
  string: CustomCommandParamType.String,
  bool: CustomCommandParamType.Boolean,
  player: CustomCommandParamType.PlayerSelector,
  entity: CustomCommandParamType.EntitySelector,
  loc: CustomCommandParamType.Location,
  item: CustomCommandParamType.ItemType,
  block: CustomCommandParamType.BlockType
};
var inv = (e) => e.getComponent("minecraft:inventory").container;
function give(e, item, n) {
  const base = typeof item === "string" ? new ItemStack(item) : item;
  let left = Math.min(Math.floor(n ?? base.amount), 64 * base.maxAmount);
  const c = inv(e);
  while (left > 0) {
    const s = base.clone();
    s.amount = Math.min(left, s.maxAmount);
    left -= s.amount;
    const rest = c.addItem(s);
    if (rest) e.dimension.spawnItem(rest, e.location);
  }
}
function load(h, key, def) {
  const s = h.getDynamicProperty(key);
  if (typeof s !== "string") return def;
  try {
    return JSON.parse(s);
  } catch {
    return def;
  }
}
function save(h, key, v) {
  h.setDynamicProperty(key, JSON.stringify(v));
}

// addons/daily/src/main.ts
var today = () => {
  const d = /* @__PURE__ */ new Date();
  return Math.floor((d.getTime() - d.getTimezoneOffset() * 6e4) / 864e5);
};
world2.afterEvents.playerSpawn.subscribe(({ player: p, initialSpawn }) => {
  if (!initialSpawn) return;
  const day = today(), last = load(p, "bonusDay", -1);
  if (last === day) return;
  const streak = last === day - 1 ? load(p, "streak", 0) + 1 : 1;
  save(p, "bonusDay", day);
  save(p, "streak", streak);
  const n = streak % 7 === 0 ? 5 : 1;
  give(p, "minecraft:emerald", n);
  p.sendMessage(`Login bonus: ${n} emerald (day ${streak} in a row)`);
});
