// generated by `node lab.mjs build` from src/ (edit src/, not this file)

// addons/jelly/src/main.ts
import { world as world2 } from "@minecraft/server";

// addons/jelly/src/kit.ts
import {
  world,
  system,
  Player,
  ItemStack,
  CommandPermissionLevel,
  CustomCommandStatus,
  CustomCommandParamType,
  DisplaySlotId
} from "@minecraft/server";
import { ActionFormData, ModalFormData, MessageFormData, FormCancelationReason } from "@minecraft/server-ui";
var PT = {
  int: CustomCommandParamType.Integer,
  float: CustomCommandParamType.Float,
  string: CustomCommandParamType.String,
  bool: CustomCommandParamType.Boolean,
  player: CustomCommandParamType.PlayerSelector,
  entity: CustomCommandParamType.EntitySelector,
  loc: CustomCommandParamType.Location,
  item: CustomCommandParamType.ItemType,
  block: CustomCommandParamType.BlockType
};
var inv = (e) => e.getComponent("minecraft:inventory").container;
function give(e, item, n) {
  const base = typeof item === "string" ? new ItemStack(item) : item;
  let left = Math.min(Math.floor(n ?? base.amount), 64 * base.maxAmount);
  const c = inv(e);
  while (left > 0) {
    const s = base.clone();
    s.amount = Math.min(left, s.maxAmount);
    left -= s.amount;
    const rest = c.addItem(s);
    if (rest) e.dimension.spawnItem(rest, e.location);
  }
}

// addons/jelly/src/main.ts
world2.afterEvents.itemCompleteUse.subscribe(({ itemStack, source }) => {
  if (itemStack.typeId !== "lab:jump_potion") return;
  source.addEffect("jump_boost", 600, { amplifier: 1 });
  give(source, "minecraft:glass_bottle", 1);
  source.sendMessage("You feel springy");
});
