// generated by `node lab.mjs build` from src/ (edit src/, not this file)

// addons/home/src/main.ts
import { world as world2 } from "@minecraft/server";

// addons/home/src/kit.ts
import {
  world,
  system,
  Player,
  ItemStack,
  CommandPermissionLevel,
  CustomCommandStatus,
  CustomCommandParamType,
  DisplaySlotId
} from "@minecraft/server";
import { ActionFormData, ModalFormData, MessageFormData, FormCancelationReason } from "@minecraft/server-ui";
var early = [];
var hooked = false;
function atStartup(fn) {
  early.push(fn);
  if (!hooked) {
    hooked = true;
    system.beforeEvents.startup.subscribe((e) => {
      for (const f of early) f(e);
    });
  }
}
var PT = {
  int: CustomCommandParamType.Integer,
  float: CustomCommandParamType.Float,
  string: CustomCommandParamType.String,
  bool: CustomCommandParamType.Boolean,
  player: CustomCommandParamType.PlayerSelector,
  entity: CustomCommandParamType.EntitySelector,
  loc: CustomCommandParamType.Location,
  item: CustomCommandParamType.ItemType,
  block: CustomCommandParamType.BlockType
};
function cmd(name, description, params, fn, op = false) {
  cmdAny(name, description, params, (p, a, o) => p ? fn(p, a, o) : "players only", op);
}
function cmdAny(name, description, params, fn, op = false) {
  const ns = name.split(":")[0];
  atStartup((e) => {
    const list = Object.entries(params).map(([k, t]) => {
      const opt = k.endsWith("?"), key = opt ? k.slice(0, -1) : k;
      if (Array.isArray(t)) {
        const en = `${ns}:${key}`;
        e.customCommandRegistry.registerEnum(en, [...t]);
        return { key, opt, p: { name: en, type: CustomCommandParamType.Enum } };
      }
      return { key, opt, p: { name: key, type: PT[t] } };
    });
    e.customCommandRegistry.registerCommand({
      name,
      description,
      permissionLevel: op ? CommandPermissionLevel.GameDirectors : CommandPermissionLevel.Any,
      mandatoryParameters: list.filter((x) => !x.opt).map((x) => x.p),
      optionalParameters: list.filter((x) => x.opt).map((x) => x.p)
    }, (o, ...v) => {
      const order = [...list.filter((x) => !x.opt), ...list.filter((x) => x.opt)];
      const a = {};
      order.forEach((x, i) => {
        a[x.key] = v[i];
      });
      const who = o.initiator ?? o.sourceEntity, p = who instanceof Player ? who : void 0;
      const tell = (r) => {
        if (typeof r === "string") {
          if (!p) console.warn(r);
          else if (p.isValid) p.sendMessage(r);
        }
      };
      system.run(() => {
        const r = fn(p, a, o);
        r instanceof Promise ? r.then(tell) : tell(r);
      });
      return { status: CustomCommandStatus.Success };
    });
  });
}
function load(h, key, def) {
  const s = h.getDynamicProperty(key);
  if (typeof s !== "string") return def;
  try {
    return JSON.parse(s);
  } catch {
    return def;
  }
}
function save(h, key, v) {
  h.setDynamicProperty(key, JSON.stringify(v));
}
var cds = /* @__PURE__ */ new Map();
function cooldown(e, key, ticks) {
  const k = e.id + "|" + key, now = system.currentTick;
  if ((cds.get(k) ?? -Infinity) > now) return false;
  cds.set(k, now + ticks);
  return true;
}

// addons/home/src/main.ts
cmd("lab:sethome", "Set your home here", {}, (p) => {
  const { x, y, z } = p.location;
  save(p, "home", { dim: p.dimension.id, x, y, z });
  return `Home set at ${Math.floor(x)} ${Math.floor(y)} ${Math.floor(z)} (${p.dimension.id.replace("minecraft:", "")})`;
});
cmd("lab:home", "Go back to your home", {}, (p) => {
  const h = load(p, "home", null);
  if (!h) return "You have no home yet: /lab:sethome";
  if (!cooldown(p, "home", 200)) return "Wait a little before going home again";
  p.teleport({ x: h.x, y: h.y, z: h.z }, { dimension: world2.getDimension(h.dim) });
  return "Welcome home";
});
