// generated by `node lab.mjs build` from src/ (edit src/, not this file)

// addons/fishcup/src/main.ts
import { world as world2, system as system2, Player as Player2 } from "@minecraft/server";

// addons/fishcup/src/kit.ts
import {
  world,
  system,
  Player,
  ItemStack,
  CommandPermissionLevel,
  CustomCommandStatus,
  CustomCommandParamType,
  DisplaySlotId
} from "@minecraft/server";
import { ActionFormData, ModalFormData, MessageFormData, FormCancelationReason } from "@minecraft/server-ui";
var early = [];
var hooked = false;
function atStartup(fn) {
  early.push(fn);
  if (!hooked) {
    hooked = true;
    system.beforeEvents.startup.subscribe((e) => {
      for (const f of early) f(e);
    });
  }
}
var PT = {
  int: CustomCommandParamType.Integer,
  float: CustomCommandParamType.Float,
  string: CustomCommandParamType.String,
  bool: CustomCommandParamType.Boolean,
  player: CustomCommandParamType.PlayerSelector,
  entity: CustomCommandParamType.EntitySelector,
  loc: CustomCommandParamType.Location,
  item: CustomCommandParamType.ItemType,
  block: CustomCommandParamType.BlockType
};
function cmd(name, description, params, fn, op = false) {
  cmdAny(name, description, params, (p, a, o) => p ? fn(p, a, o) : "players only", op);
}
function cmdAny(name, description, params, fn, op = false) {
  const ns = name.split(":")[0];
  atStartup((e) => {
    const list = Object.entries(params).map(([k, t]) => {
      const opt = k.endsWith("?"), key = opt ? k.slice(0, -1) : k;
      if (Array.isArray(t)) {
        const en = `${ns}:${key}`;
        e.customCommandRegistry.registerEnum(en, [...t]);
        return { key, opt, p: { name: en, type: CustomCommandParamType.Enum } };
      }
      return { key, opt, p: { name: key, type: PT[t] } };
    });
    e.customCommandRegistry.registerCommand({
      name,
      description,
      permissionLevel: op ? CommandPermissionLevel.GameDirectors : CommandPermissionLevel.Any,
      mandatoryParameters: list.filter((x) => !x.opt).map((x) => x.p),
      optionalParameters: list.filter((x) => x.opt).map((x) => x.p)
    }, (o, ...v) => {
      const order = [...list.filter((x) => !x.opt), ...list.filter((x) => x.opt)];
      const a = {};
      order.forEach((x, i) => {
        a[x.key] = v[i];
      });
      const who = o.initiator ?? o.sourceEntity, p = who instanceof Player ? who : void 0;
      const tell = (r) => {
        if (typeof r === "string") {
          if (!p) console.warn(r);
          else if (p.isValid) p.sendMessage(r);
        }
      };
      system.run(() => {
        const r = fn(p, a, o);
        r instanceof Promise ? r.then(tell) : tell(r);
      });
      return { status: CustomCommandStatus.Success };
    });
  });
}
var inv = (e) => e.getComponent("minecraft:inventory").container;
function give(e, item, n) {
  const base = typeof item === "string" ? new ItemStack(item) : item;
  let left = Math.min(Math.floor(n ?? base.amount), 64 * base.maxAmount);
  const c = inv(e);
  while (left > 0) {
    const s = base.clone();
    s.amount = Math.min(left, s.maxAmount);
    left -= s.amount;
    const rest = c.addItem(s);
    if (rest) e.dimension.spawnItem(rest, e.location);
  }
}
function score(id, name = id, show) {
  const o = world.scoreboard.getObjective(id) ?? world.scoreboard.addObjective(id, name);
  if (show) world.scoreboard.setObjectiveAtDisplaySlot(DisplaySlotId[show], { objective: o });
  return o;
}

// addons/fishcup/src/main.ts
var FISH = /* @__PURE__ */ new Set(["minecraft:cod", "minecraft:salmon", "minecraft:tropical_fish", "minecraft:pufferfish"]);
var OBJ = "fishcup";
var endsAt = -1;
var reeled = /* @__PURE__ */ new Map();
var running = () => endsAt >= 0;
cmd("lab:fish", "Start a fishing contest", { "seconds?": "int" }, (p, a) => {
  if (running()) return "A contest is already running";
  const secs = Math.max(10, Math.min(600, a.seconds ?? 180));
  world2.scoreboard.getObjective(OBJ) && world2.scoreboard.removeObjective(OBJ);
  score(OBJ, "Fish caught", "Sidebar");
  endsAt = system2.currentTick + secs * 20;
  world2.sendMessage(`Fishing contest started: ${secs} seconds`);
  system2.runTimeout(finish, secs * 20);
  return void 0;
});
world2.beforeEvents.itemUse.subscribe(({ source, itemStack }) => {
  if (running() && itemStack.typeId === "minecraft:fishing_rod") reeled.set(source.name, system2.currentTick);
});
world2.afterEvents.playerInventoryItemChange.subscribe(({ player, itemStack, beforeItemStack }) => {
  if (!running() || !itemStack || !FISH.has(itemStack.typeId)) return;
  if (system2.currentTick - (reeled.get(player.name) ?? -999) > 60) return;
  const before = beforeItemStack?.typeId === itemStack.typeId ? beforeItemStack.amount : 0;
  const n = itemStack.amount - before;
  if (n > 0) world2.scoreboard.getObjective(OBJ)?.addScore(player, n);
});
function finish() {
  endsAt = -1;
  const o = world2.scoreboard.getObjective(OBJ);
  const scores = (o?.getScores() ?? []).filter((s) => s.score > 0).sort((a, b) => b.score - a.score);
  const top = scores[0], winner = top?.participant.getEntity();
  if (!top) world2.sendMessage("Fishing contest over: nobody caught a fish");
  else if (winner instanceof Player2) {
    give(winner, "minecraft:diamond", 3);
    world2.sendMessage(`Fishing contest over: ${winner.name} wins with ${top.score} fish (3 diamonds)`);
  } else world2.sendMessage(`Fishing contest over: ${top.participant.displayName} wins with ${top.score} fish (left before the end: no prize)`);
  if (o) world2.scoreboard.removeObjective(o);
}
