// generated by `node lab.mjs build` from src/ (edit src/, not this file)

// addons/zone/src/main.ts
import { world as world2 } from "@minecraft/server";

// addons/zone/src/kit.ts
import {
  world,
  system,
  Player,
  ItemStack,
  CommandPermissionLevel,
  CustomCommandStatus,
  CustomCommandParamType,
  DisplaySlotId
} from "@minecraft/server";
import { ActionFormData, ModalFormData, MessageFormData, FormCancelationReason } from "@minecraft/server-ui";
var PT = {
  int: CustomCommandParamType.Integer,
  float: CustomCommandParamType.Float,
  string: CustomCommandParamType.String,
  bool: CustomCommandParamType.Boolean,
  player: CustomCommandParamType.PlayerSelector,
  entity: CustomCommandParamType.EntitySelector,
  loc: CustomCommandParamType.Location,
  item: CustomCommandParamType.ItemType,
  block: CustomCommandParamType.BlockType
};
var inv = (e) => e.getComponent("minecraft:inventory").container;
function give(e, item, n) {
  const base = typeof item === "string" ? new ItemStack(item) : item;
  let left = Math.min(Math.floor(n ?? base.amount), 64 * base.maxAmount);
  const c = inv(e);
  while (left > 0) {
    const s = base.clone();
    s.amount = Math.min(left, s.maxAmount);
    left -= s.amount;
    const rest = c.addItem(s);
    if (rest) e.dimension.spawnItem(rest, e.location);
  }
}
function once(h, key) {
  const k = "kit:once:" + key;
  if (h.getDynamicProperty(k)) return false;
  h.setDynamicProperty(k, true);
  return true;
}
function every(ticks, fn) {
  return system.runInterval(() => {
    for (const p of world.getAllPlayers()) fn(p);
  }, ticks);
}

// addons/zone/src/main.ts
var inside = /* @__PURE__ */ new Set();
every(5, (p) => {
  const { x, z } = p.location, now = x >= 3 && x <= 6 && z >= 3 && z <= 6;
  if (now && !inside.has(p.name)) p.sendMessage("Welcome to the zone");
  if (now) inside.add(p.name);
  else inside.delete(p.name);
});
world2.afterEvents.playerSpawn.subscribe((e) => {
  if (e.initialSpawn && once(e.player, "bread")) give(e.player, "minecraft:bread", 1);
});
