// generated by `node lab.mjs build` from src/ (edit src/, not this file)

// addons/coins/src/kit.ts
import {
  world,
  system,
  Player,
  ItemStack,
  CommandPermissionLevel,
  CustomCommandStatus,
  CustomCommandParamType,
  DisplaySlotId
} from "@minecraft/server";
import { ActionFormData, ModalFormData, MessageFormData, FormCancelationReason } from "@minecraft/server-ui";
var early = [];
var hooked = false;
function atStartup(fn) {
  early.push(fn);
  if (!hooked) {
    hooked = true;
    system.beforeEvents.startup.subscribe((e) => {
      for (const f of early) f(e);
    });
  }
}
var PT = {
  int: CustomCommandParamType.Integer,
  float: CustomCommandParamType.Float,
  string: CustomCommandParamType.String,
  bool: CustomCommandParamType.Boolean,
  player: CustomCommandParamType.PlayerSelector,
  entity: CustomCommandParamType.EntitySelector,
  loc: CustomCommandParamType.Location,
  item: CustomCommandParamType.ItemType,
  block: CustomCommandParamType.BlockType
};
function cmd(name, description, params, fn, op = false) {
  cmdAny(name, description, params, (p, a, o) => p ? fn(p, a, o) : "players only", op);
}
function cmdAny(name, description, params, fn, op = false) {
  const ns = name.split(":")[0];
  atStartup((e) => {
    const list = Object.entries(params).map(([k, t]) => {
      const opt = k.endsWith("?"), key = opt ? k.slice(0, -1) : k;
      if (Array.isArray(t)) {
        const en = `${ns}:${key}`;
        e.customCommandRegistry.registerEnum(en, [...t]);
        return { key, opt, p: { name: en, type: CustomCommandParamType.Enum } };
      }
      return { key, opt, p: { name: key, type: PT[t] } };
    });
    e.customCommandRegistry.registerCommand({
      name,
      description,
      permissionLevel: op ? CommandPermissionLevel.GameDirectors : CommandPermissionLevel.Any,
      mandatoryParameters: list.filter((x) => !x.opt).map((x) => x.p),
      optionalParameters: list.filter((x) => x.opt).map((x) => x.p)
    }, (o, ...v) => {
      const order = [...list.filter((x) => !x.opt), ...list.filter((x) => x.opt)];
      const a = {};
      order.forEach((x, i) => {
        a[x.key] = v[i];
      });
      const who = o.initiator ?? o.sourceEntity, p = who instanceof Player ? who : void 0;
      const tell = (r) => {
        if (typeof r === "string") {
          if (!p) console.warn(r);
          else if (p.isValid) p.sendMessage(r);
        }
      };
      system.run(() => {
        const r = fn(p, a, o);
        r instanceof Promise ? r.then(tell) : tell(r);
      });
      return { status: CustomCommandStatus.Success };
    });
  });
}
var inv = (e) => e.getComponent("minecraft:inventory").container;
function give(e, item, n) {
  const base = typeof item === "string" ? new ItemStack(item) : item;
  let left = Math.min(Math.floor(n ?? base.amount), 64 * base.maxAmount);
  const c = inv(e);
  while (left > 0) {
    const s = base.clone();
    s.amount = Math.min(left, s.maxAmount);
    left -= s.amount;
    const rest = c.addItem(s);
    if (rest) e.dimension.spawnItem(rest, e.location);
  }
}
function load(h, key, def) {
  const s = h.getDynamicProperty(key);
  if (typeof s !== "string") return def;
  try {
    return JSON.parse(s);
  } catch {
    return def;
  }
}
function save(h, key, v) {
  h.setDynamicProperty(key, JSON.stringify(v));
}

// addons/coins/src/main.ts
var today = () => {
  const d = /* @__PURE__ */ new Date();
  return Math.floor((d.getTime() - d.getTimezoneOffset() * 6e4) / 864e5);
};
cmd("lab:coins", "Get a coin once a day", {}, (p) => {
  const day = today();
  if (load(p, "coinDay", -1) === day) return "Already claimed today";
  save(p, "coinDay", day);
  give(p, "minecraft:gold_nugget", 1);
  return "You got a coin";
});
