// generated by `node lab.mjs build` from src/ (edit src/, not this file)

// addons/shop/src/main.ts
import { world as world2 } from "@minecraft/server";

// addons/shop/src/kit.ts
import {
  world,
  system,
  Player,
  ItemStack,
  CommandPermissionLevel,
  CustomCommandStatus,
  CustomCommandParamType,
  DisplaySlotId
} from "@minecraft/server";
import { ActionFormData, ModalFormData, MessageFormData, FormCancelationReason } from "@minecraft/server-ui";
var early = [];
var hooked = false;
function atStartup(fn) {
  early.push(fn);
  if (!hooked) {
    hooked = true;
    system.beforeEvents.startup.subscribe((e) => {
      for (const f of early) f(e);
    });
  }
}
var PT = {
  int: CustomCommandParamType.Integer,
  float: CustomCommandParamType.Float,
  string: CustomCommandParamType.String,
  bool: CustomCommandParamType.Boolean,
  player: CustomCommandParamType.PlayerSelector,
  entity: CustomCommandParamType.EntitySelector,
  loc: CustomCommandParamType.Location,
  item: CustomCommandParamType.ItemType,
  block: CustomCommandParamType.BlockType
};
function cmd(name, description, params, fn, op = false) {
  cmdAny(name, description, params, (p, a, o) => p ? fn(p, a, o) : "players only", op);
}
function cmdAny(name, description, params, fn, op = false) {
  const ns = name.split(":")[0];
  atStartup((e) => {
    const list = Object.entries(params).map(([k, t]) => {
      const opt = k.endsWith("?"), key = opt ? k.slice(0, -1) : k;
      if (Array.isArray(t)) {
        const en = `${ns}:${key}`;
        e.customCommandRegistry.registerEnum(en, [...t]);
        return { key, opt, p: { name: en, type: CustomCommandParamType.Enum } };
      }
      return { key, opt, p: { name: key, type: PT[t] } };
    });
    e.customCommandRegistry.registerCommand({
      name,
      description,
      permissionLevel: op ? CommandPermissionLevel.GameDirectors : CommandPermissionLevel.Any,
      mandatoryParameters: list.filter((x) => !x.opt).map((x) => x.p),
      optionalParameters: list.filter((x) => x.opt).map((x) => x.p)
    }, (o, ...v) => {
      const order = [...list.filter((x) => !x.opt), ...list.filter((x) => x.opt)];
      const a = {};
      order.forEach((x, i) => {
        a[x.key] = v[i];
      });
      const who = o.initiator ?? o.sourceEntity, p = who instanceof Player ? who : void 0;
      const tell = (r) => {
        if (typeof r === "string") {
          if (!p) console.warn(r);
          else if (p.isValid) p.sendMessage(r);
        }
      };
      system.run(() => {
        const r = fn(p, a, o);
        r instanceof Promise ? r.then(tell) : tell(r);
      });
      return { status: CustomCommandStatus.Success };
    });
  });
}
async function ask(p, form, tries = 60) {
  for (let i = 0; i < tries && p.isValid; i++) {
    let r;
    try {
      r = await form.show(p);
    } catch {
      return void 0;
    }
    if (!r.canceled) return r;
    if (r.cancelationReason !== FormCancelationReason.UserBusy) return void 0;
    await system.waitTicks(5);
  }
  return void 0;
}
async function menu(p, title, buttons, body) {
  const f = new ActionFormData().title(title);
  if (body) f.body(body);
  for (const [label] of buttons) f.button(label);
  const r = await ask(p, f);
  if (r?.selection === void 0) return void 0;
  await buttons[r.selection]?.[1]?.(p);
  return r.selection;
}
var inv = (e) => e.getComponent("minecraft:inventory").container;
function give(e, item, n) {
  const base = typeof item === "string" ? new ItemStack(item) : item;
  let left = Math.min(Math.floor(n ?? base.amount), 64 * base.maxAmount);
  const c = inv(e);
  while (left > 0) {
    const s = base.clone();
    s.amount = Math.min(left, s.maxAmount);
    left -= s.amount;
    const rest = c.addItem(s);
    if (rest) e.dimension.spawnItem(rest, e.location);
  }
}
function once(h, key) {
  const k = "kit:once:" + key;
  if (h.getDynamicProperty(k)) return false;
  h.setDynamicProperty(k, true);
  return true;
}
function score(id, name = id, show) {
  const o = world.scoreboard.getObjective(id) ?? world.scoreboard.addObjective(id, name);
  if (show) world.scoreboard.setObjectiveAtDisplaySlot(DisplaySlotId[show], { objective: o });
  return o;
}

// addons/shop/src/main.ts
var GOODS = [["Bread", "minecraft:bread", 5], ["Iron Ingot", "minecraft:iron_ingot", 20], ["Diamond", "minecraft:diamond", 100]];
var coins = () => score("coins", "Coins", "Sidebar");
var bal = (p) => coins().hasParticipant(p) ? coins().getScore(p) ?? 0 : 0;
world2.afterEvents.playerSpawn.subscribe(({ player, initialSpawn }) => {
  if (initialSpawn && once(player, "coins")) coins().addScore(player, 50);
  else coins().addScore(player, 0);
});
cmd("lab:shop", "Open the shop", {}, async (p) => {
  await menu(p, "Shop", GOODS.map(([name, id, price]) => [`${name} - ${price} coins`, (q) => {
    if (bal(q) < price) {
      q.sendMessage(`Not enough coins: ${name} costs ${price}, you have ${bal(q)}`);
      return;
    }
    coins().addScore(q, -price);
    give(q, id, 1);
    q.sendMessage(`Bought ${name} for ${price} coins (${bal(q)} left)`);
  }]), `You have ${bal(p)} coins`);
  return void 0;
});
cmd("lab:pay", "Send coins to a player", { who: "player", amount: "int" }, (p, a) => {
  const to = a.who ?? [];
  if (to.length !== 1) return "Name one player";
  const [q] = to;
  if (q.name === p.name) return "You cannot pay yourself";
  if (a.amount <= 0) return "The amount must be at least 1";
  if (bal(p) < a.amount) return `Not enough coins: you have ${bal(p)}`;
  coins().addScore(p, -a.amount);
  coins().addScore(q, a.amount);
  q.sendMessage(`${p.name} sent you ${a.amount} coins`);
  return `Sent ${a.amount} coins to ${q.name}`;
});
