// generated by `node lab.mjs build` from src/ (edit src/, not this file)

// addons/jsonui_demo/src/main.ts
import { world as world2, system as system2 } from "@minecraft/server";
import { ActionFormData as ActionFormData2 } from "@minecraft/server-ui";

// addons/jsonui_demo/src/kit.ts
import {
  world,
  system,
  Player,
  ItemStack,
  CommandPermissionLevel,
  CustomCommandStatus,
  CustomCommandParamType,
  DisplaySlotId
} from "@minecraft/server";
import { ActionFormData, ModalFormData, MessageFormData, FormCancelationReason } from "@minecraft/server-ui";
var early = [];
var hooked = false;
function atStartup(fn) {
  early.push(fn);
  if (!hooked) {
    hooked = true;
    system.beforeEvents.startup.subscribe((e) => {
      for (const f of early) f(e);
    });
  }
}
var PT = {
  int: CustomCommandParamType.Integer,
  float: CustomCommandParamType.Float,
  string: CustomCommandParamType.String,
  bool: CustomCommandParamType.Boolean,
  player: CustomCommandParamType.PlayerSelector,
  entity: CustomCommandParamType.EntitySelector,
  loc: CustomCommandParamType.Location,
  item: CustomCommandParamType.ItemType,
  block: CustomCommandParamType.BlockType
};
function cmd(name, description, params, fn, op = false) {
  cmdAny(name, description, params, (p, a, o) => p ? fn(p, a, o) : "players only", op);
}
function cmdAny(name, description, params, fn, op = false) {
  const ns = name.split(":")[0];
  atStartup((e) => {
    const list = Object.entries(params).map(([k, t]) => {
      const opt = k.endsWith("?"), key = opt ? k.slice(0, -1) : k;
      if (Array.isArray(t)) {
        const en = `${ns}:${key}`;
        e.customCommandRegistry.registerEnum(en, [...t]);
        return { key, opt, p: { name: en, type: CustomCommandParamType.Enum } };
      }
      return { key, opt, p: { name: key, type: PT[t] } };
    });
    e.customCommandRegistry.registerCommand({
      name,
      description,
      permissionLevel: op ? CommandPermissionLevel.GameDirectors : CommandPermissionLevel.Any,
      mandatoryParameters: list.filter((x) => !x.opt).map((x) => x.p),
      optionalParameters: list.filter((x) => x.opt).map((x) => x.p)
    }, (o, ...v) => {
      const order = [...list.filter((x) => !x.opt), ...list.filter((x) => x.opt)];
      const a = {};
      order.forEach((x, i) => {
        a[x.key] = v[i];
      });
      const who = o.initiator ?? o.sourceEntity, p = who instanceof Player ? who : void 0;
      const tell = (r) => {
        if (typeof r === "string") {
          if (!p) console.warn(r);
          else if (p.isValid) p.sendMessage(r);
        }
      };
      system.run(() => {
        const r = fn(p, a, o);
        r instanceof Promise ? r.then(tell) : tell(r);
      });
      return { status: CustomCommandStatus.Success };
    });
  });
}
async function ask(p, form, tries = 60) {
  for (let i = 0; i < tries && p.isValid; i++) {
    let r;
    try {
      r = await form.show(p);
    } catch {
      return void 0;
    }
    if (!r.canceled) return r;
    if (r.cancelationReason !== FormCancelationReason.UserBusy) return void 0;
    await system.waitTicks(5);
  }
  return void 0;
}

// addons/jsonui_demo/src/main.ts
var DEMO = "\xA7d\xA7e\xA7m\xA7o\xA7r";
async function menu(p) {
  const f = new ActionFormData2().title(DEMO + "JSON UI Demo").body("This form is drawn by rp/ui/server_form.json.").button("Diamond", "textures/items/diamond").button("Emerald", "textures/items/emerald").button("Close");
  const r = await ask(p, f);
  const pick = r === void 0 || r.canceled || r.selection === void 0 ? "closed" : ["diamond", "emerald", "close"][r.selection];
  console.log(`DEMO ${p.name} picked ${pick}`);
  return pick;
}
cmd("lab:menu", "Open the JSON UI demo form", {}, (p) => {
  void menu(p);
  return "DEMO opening";
});
cmdAny("lab:menuall", "Open the JSON UI demo form for every player", {}, () => {
  const ps = world2.getAllPlayers();
  for (const p of ps) void menu(p);
  return `DEMO shown to ${ps.length}`;
});
system2.afterEvents.scriptEventReceive.subscribe((e) => {
  if (e.id !== "demo:open") return;
  const ps = world2.getAllPlayers();
  for (const p of ps) void menu(p);
  console.log(`DEMO shown to ${ps.length}`);
});
export {
  DEMO
};
